name: Python Install
on:
  push:
    paths:
      - 'python/**'
jobs:
  install:
    name: Install on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install Package
      run: pip install ./python/
